### ISSUE TITLE
很实用的日历感谢

### ISSUE THREAD

**Issue by zackzeng00** [toosean/ChinaPublicCalendar#1]
补充一个看是否能实现
电影是否能加入豆瓣跳转链接？

**Comment by toosean** [comment]
@zackzeng00 跳转链接这个跟具体的实例app实现有关系，你用什么app订阅日历呢？

**Comment by zackzeng00** [comment]
> @zackzeng00 跳转链接这个跟具体的实例app实现有关系，你用什么app订阅日历呢？

主要使用谷歌日历与icloud日历.
目前是使用谷歌日历订阅电影ical
使用客户端是 fantastical.
期望是"是否能在日历描述字段里面加入"该日历电影"的豆瓣跳转链接"

**Comment by toosean** [comment]
@zackzeng00 我已经在日历项目中直接加入了豆瓣的链接，这样子经过测试能比较好的兼容 Google 日历和 Outlook 的日历。
