### ISSUE TITLE
有没有添加ios订阅的想法？

### ISSUE THREAD

**Issue by Aaloone** [toosean/ChinaPublicCalendar#3]
ios14 日历订阅一直出错，这个订阅难道还需要特别设置吗？

**Comment by toosean** [comment]
@Aaloone 抱歉，没有哎 IOS 上试过，我找个手机试试。

**Comment by YGGcn** [comment]
在Mac日历上订阅是可以正常使用的，奇怪的是无法将日程信息同步到iOS日历上；尝试在iOS日历中手动添加订阅时出现“无法使用SSL连接”“无法验证账户信息”“此账户可能无法连通日历”的提示，无法正常完成订阅。非常想在iOS日历上使用这些公共日历，希望能修复这个BUG，谢谢！

**Comment by toosean** [comment]
#5 我一直没有没办法复现这个问题，后来发现可能 raw.githubusercontent.com 被墙可能造成的问题。
现在可以用 https://toosean.github.io/ChinaPublicCalendar/Calendar/cal.ics 这个地址代替即可。
