### ISSUE TITLE
日历ics文件内容空白，无法订阅有效的日历内容

### ISSUE THREAD

**Issue by YGGcn** [toosean/ChinaPublicCalendar#8]
使用最新的订阅链接在iOS日历和Outlook日历订阅后发现没有日历内容，以“内地电影上映日期”日历为例，打开下载到本地的ics文件后只看到了以下文本信息：
`BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 4.0//EN
VERSION:2.0
X-WR-CALNAME:内地电影上映日期
END:VCALENDAR`
希望问题可以得到解决，非常感谢！

**Comment by toosean** [comment]
@YGGcn sorry,急急忙忙出了点问题，已经修复了。
