### ISSUE TITLE
2021年劳动节假日错误

### ISSUE THREAD

**Issue by JarmoHu** [toosean/ChinaPublicCalendar#9]
2021年劳动节休假是从5月1日到5月5日，但是这个日历显示的是5月4日就结束了。

**Comment by JarmoHu** [comment]
不对，貌似日历文件是对的，但是导入到outlook就会少最后一天？

**Comment by JarmoHu** [comment]
我查阅了如下资料：
https://tools.ietf.org/html/rfc5545

在3.6.1小节，page55中发现了如下段落。

> The following is an example of the "VEVENT" calendar component used to represent a multi-day event scheduled from June 28th, 2007 to July 8th, 2007 inclusively.  Note that the "DTEND" property is set to July 9th, 2007, since the "DTEND" property specifies the non-inclusive end of the event.
> 
> BEGIN:VEVENT
> UID:20070423T123432Z-541111@example.com
> DTSTAMP:20070423T123432Z
> DTSTART;VALUE=DATE:20070628
> DTEND;VALUE=DATE:20070709
> SUMMARY:Festival International de Jazz de Montreal
> TRANSP:TRANSPARENT
> END:VEVENT

也就是说如果劳动节放假是5月5日结束，那么就要写成5月6日，DTEND;VALUE=DATE:20210506

**Comment by toosean** [comment]
大佬太细新了，实在感谢，之前没有注意到这个问题。

**Comment by hakil** [comment]
Google日历中工作节假日历也同样少一天，例如端午节放假至14日但在日历中显示的是13日。
日历文件中截止日期设置的是14日，综上所述应该在截止日期上加一日。

**Comment by JarmoHu** [comment]
> 
> 
> 大佬太细心了，实在感谢，之前没有注意到这个问题。

不准备更新一波？

**Comment by toosean** [comment]
> > 大佬太细心了，实在感谢，之前没有注意到这个问题。
> 
> 不准备更新一波

其实已经弄好了，但是最近一直在外地。自动更新 github 的程序运行在一个内网机器，我没法远程更新那个程序。

**Comment by toosean** [comment]
@JarmoHu 更新了，再次感谢指出错误。
